######################## GNU General Public License 3.0 ########################
##                                                                            ##
## Copyright (C) 2023 Kevin Matthes                                           ##
##                                                                            ##
## This program is free software: you can redistribute it and/or modify       ##
## it under the terms of the GNU General Public License as published by       ##
## the Free Software Foundation, either version 3 of the License, or          ##
## (at your option) any later version.                                        ##
##                                                                            ##
## This program is distributed in the hope that it will be useful,            ##
## but WITHOUT ANY WARRANTY; without even the implied warranty of             ##
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              ##
## GNU General Public License for more details.                               ##
##                                                                            ##
## You should have received a copy of the GNU General Public License          ##
## along with this program.  If not, see <https://www.gnu.org/licenses/>.     ##
##                                                                            ##
################################################################################

################################################################################
##
##  AUTHOR      Kevin Matthes
##  BRIEF       The CI of this project.
##  COPYRIGHT   GPL-3.0
##  DATE        2023
##  FILE        ci.yml
##  NOTE        See `LICENSE' for full license.
##              See `README.md' for project details.
##
################################################################################

name: ci

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  cffconvert:
    name: cffconvert
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
        with:
          persist-credentials: false

      - name: cffconvert
        uses: citation-file-format/cffconvert-github-action@2.0.0
        with:
          args: --validate

  selftest-major-auto:
    name: selftest-major-auto
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
        with:
          persist-credentials: false

      - name: release
        uses: ./
        with:
          release: major

  selftest-major-false:
    name: selftest-major-false
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
        with:
          persist-credentials: false

      - name: release
        uses: ./
        with:
          cff: false
          release: major

  selftest-major-true:
    name: selftest-major-true
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
        with:
          persist-credentials: false

      - name: release
        uses: ./
        with:
          cff: true
          release: major

  selftest-minor-auto:
    name: selftest-minor-auto
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
        with:
          persist-credentials: false

      - name: release
        uses: ./
        with:
          release: minor

  selftest-minor-false:
    name: selftest-minor-false
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
        with:
          persist-credentials: false

      - name: release
        uses: ./
        with:
          cff: false
          release: minor

  selftest-minor-true:
    name: selftest-minor-true
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
        with:
          persist-credentials: false

      - name: release
        uses: ./
        with:
          cff: true
          release: minor

  selftest-patch-auto:
    name: selftest-patch-auto
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
        with:
          persist-credentials: false

      - name: release
        uses: ./
        with:
          release: patch

  selftest-patch-false:
    name: selftest-patch-false
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
        with:
          persist-credentials: false

      - name: release
        uses: ./
        with:
          cff: false
          release: patch

  selftest-patch-true:
    name: selftest-patch-true
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
        with:
          persist-credentials: false

      - name: release
        uses: ./
        with:
          cff: true
          release: patch

################################################################################
